# Infrastructure-as-Code TestKit for Ubuntu
#
# VERSION: 18.04
LABEL version="18.04"

FROM ubuntu:18.04

ADD requirements.txt requirements.txt

RUN apt update &&\
    apt full-upgrade -y &&\
    apt install -y python-pip python3-pip wget jq awscli google-cloud-sdk gzip unzip&&\
    apt autoremove -y &&\
    apt autoclean -y &&\
    pip install --upgrade -r requirements.txt &&\
    pip3 install --upgrade -r requirements.txt &&\
    wget -q -O terraform.zip terraform.zip https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip &&\
    unzip terraform.zip -d /usr/bin/ &&\
    wget -q -O packer.zip https://releases.hashicorp.com/packer/1.3.2/packer_1.3.2_linux_amd64.zip &&\
    unzip packer.zip -d /usr/bin/ &&\
    wget -q -O /usr/bin/terratest_log_parser https://github.com/gruntwork-io/terratest/releases/download/v0.13.13/terratest_log_parser_linux_amd64

ENTRYPOINT [ "/bin/bash", "-c" ]
